/// Shared code for the S.A.G.I.P. mobile app and web dashboard: design
/// tokens and theme, domain models, repository interfaces with mock and
/// Supabase implementations, algorithms, and shared widgets.
library;

export 'src/algorithms/alert_thresholds.dart';
export 'src/algorithms/analytics.dart';
export 'src/algorithms/dbscan.dart';
export 'src/algorithms/dijkstra.dart';
export 'src/algorithms/incident_classifier.dart';
export 'src/algorithms/polyline.dart';
export 'src/algorithms/priority.dart';
export 'src/algorithms/report_draft.dart';
export 'src/algorithms/road_graph.dart';
export 'src/algorithms/road_router.dart';
export 'src/algorithms/routing_log.dart';
export 'src/algorithms/setting_checks.dart';
export 'src/algorithms/sos_sms.dart';
export 'src/algorithms/unit_suggester.dart';
export 'src/data/manila_barangays.dart';
export 'src/format.dart';
export 'src/mock/live_value.dart';
export 'src/mock/mock_backend.dart';
export 'src/mock/mock_mobile_backend.dart';
export 'src/mock/mock_mobile_repositories.dart';
export 'src/mock/mock_repositories.dart';
export 'src/mock/mock_seed.dart' show MockSeed;
export 'src/models/account.dart';
export 'src/models/alerts.dart';
export 'src/models/analytics.dart';
export 'src/models/assignment.dart';
export 'src/models/crowd_report.dart';
export 'src/models/enums.dart';
export 'src/models/geo_point.dart';
export 'src/models/hazard_report.dart';
export 'src/models/incident.dart';
export 'src/models/ndrrmc.dart';
export 'src/models/offline.dart';
export 'src/models/people.dart';
export 'src/models/records.dart';
export 'src/models/response_unit.dart';
export 'src/models/road_route.dart';
export 'src/models/settings.dart';
export 'src/models/sos.dart';
export 'src/offline/cached_repositories.dart';
export 'src/offline/mobile_server.dart';
export 'src/offline/outbox.dart';
export 'src/offline/outbox_repositories.dart';
export 'src/offline/streams.dart';
export 'src/offline/sync_engine.dart';
export 'src/repositories/repositories.dart';
export 'src/supabase/supabase_repositories.dart';
export 'src/theme/sagip_colors.dart';
export 'src/theme/sagip_palette.dart';
export 'src/theme/sagip_theme.dart';
export 'src/theme/sagip_tokens.dart';
export 'src/widgets/brand.dart';
export 'src/widgets/offline_widgets.dart';
export 'src/widgets/responder_widgets.dart';
export 'src/widgets/sagip_chip.dart';
export 'src/widgets/sagip_map.dart';
export 'src/widgets/sos_button.dart';
export 'src/widgets/state_views.dart';
export 'src/widgets/status_visuals.dart';
